apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seminar-nextjs
  namespace: argocd
  annotations:
    notifications.argoproj.io/triggers: on-deployed,on-health-degraded
spec:
  project: default
  source:
    repoURL: https://github.com/mrfour4/seminar-gitops
    path: nextjs
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
