---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: seminar-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgCESHswYa0mbTV/zm6YDyVGCT4F9ztTMZTfmn8FGCFMSX2jlMoLqE70BXAU9RrVAlHSvODLOLm92fkdHktPn7+CoVaXHHTw9UrXUqtqKtZsZbWuR0gbOsLkMVISZosuul0R2m4uDdutiiO+zlV2C8/ZTtJSvzbXYq/kXpj06ziZmjBconrsflY2d73nIXoahfRt5MKUE9hxb6zgLcWpXOWyMv+Ps+XCzta+wyImZkwNpBzaA4Bu8EakmLrU9/j0BOI5d7P/cKe0FbT/D/xZHjyyLR7qOiDALUskqbs6CO5vf+DrrjUMih9sTXdC48H5qE73cCNjXLmRpmMulAHZi/j+ISwlnH1Y6JXuYZ31suO0fPr8DZi/ve1v78GihVSqR4lxAI9HXgeq1OLIoz2mS6VpiSbaBG0sCaAFY0RuMY1W4mQ+R3kyPqHxa1DCClsx9pCxIoxLjNov8IvXNAjesMzgs3qRyzeBoL4IiaRzn8Df0lJ9kubuS9/fhe8fIq2QVs7ilGLGsiyqQZuJtSAHub9zS9HfHzMPL4S1mwU4C0KRapyuP8gu7j9+2t8rIxI7ulGUOJrMyIOlLAfDaWwNFv3l4LfXZaTxgYIc6EWl7vzCdrC9XlNzN/xdcTOVRhdLU2KBMqp9MTyg/d08b8qLvKVHfbM79TpThUiT9b2uS4CiJSgzvvYPdToqFxsiKFIEGgOgl/eWf4KvSw9Dk/FtShx6yJ/a6nziJ4d/jMgw4SgjF165AsrfCw828hxoL4XPO612OJMtbYx7lo2CKNvDAg==
  template:
    metadata:
      creationTimestamp: null
      name: seminar-secret
      namespace: default
    type: Opaque
