apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
