image:
  repository: mrfour4uit/seminar-demo
  tag: 1118ef7486d0d9542453a6a3d364a6ddc2606fe4
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"