image:
  repository: mrfour4uit/seminar-demo
  tag: c782b75d917731475f947158abe9e145dbc9e0d6
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"