image:
  repository: mrfour4uit/seminar-demo
  tag: 89882986fd1ca4eecd9dcd8b8375d8de6cb6dc36
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"