image:
  repository: mrfour4uit/seminar-demo
  tag: fcdf36d8f12df737f0f373f4cc93ce84045853d0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"