image:
  repository: mrfour4uit/seminar-demo
  tag: c18304bc3056dc2ef2a2be72104d6a886bcaaaaa
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"