image:
  repository: mrfour4uit/seminar-demo
  tag: ef36bf88e1ee8f07f0cbcc6dd9d558ce3da47203
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"