image:
  repository: mrfour4uit/seminar-demo
  tag: 095cf0c72f304b8ee75e43fd07e4df4df3b2e33c
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"