image:
  repository: mrfour4uit/seminar-demo
  tag: 4b314ffe897c10c73b8ab002a7d4411e58fcb6dc
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"