image:
  repository: mrfour4uit/seminar-demo
  tag: "does-not-exist-2"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"