image:
  repository: mrfour4uit/seminar-demo
  tag: 026a96d906644db9c77ca9beb0fde8794e6dcbd2
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"