image:
  repository: mrfour4uit/seminar-demo
  tag: 4903cec43c92c0acbf115952447884c424184938
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"