image:
  repository: mrfour4uit/seminar-demo
  tag: fc7a1c58609772fcc32649c876e24d714f7e1aaa
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"