image:
  repository: mrfour4uit/seminar-demo
  tag: 3e7bf82a465c12747d4a88ad91c9446e204ba575
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"