image:
  repository: mrfour4uit/seminar-demo
  tag: 3db74a6293a6f1d8321a2313352ac4915ace26f9
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

replicaCount: 1

env:
  - name: NEXT_PUBLIC_APP_URL
    value: "http://seminar.local"