name: Auto Rollback on Degraded

on:
  repository_dispatch:
    types: [argo-degraded]

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Hiển thị log commit gần nhất
        run: git log --oneline -n 3

      - name: Revert commit cuối cùng
        run: |
          git revert --no-edit HEAD
          git push origin main
