name: Revert values.yaml to specific commit

on:
  repository_dispatch:
    types: [argo-degraded]

jobs:
  revert:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPO: mrfour4/seminar-gitops
      GH_PAT: ${{ secrets.GH_PAT_WEBHOOK }}

    steps:
      - name: Clone repository manually
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git clone https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPO}.git
          cd seminar-gitops
          echo "REPO_CLONED=true" >> $GITHUB_ENV

      - name: Get commit ID
        if: env.REPO_CLONED == 'true'
        run: echo "commit_id=${{ github.event.client_payload.healthy_revision }}" >> $GITHUB_ENV

      - name: Revert values.yaml
        if: env.REPO_CLONED == 'true'
        run: |
          cd seminar-gitops
          git checkout ${{ env.commit_id }} -- nextjs/values.yaml
          git add nextjs/values.yaml
          git commit -m "Revert values.yaml to healthy commit ${{ env.commit_id }}"

      - name: Push changes
        if: env.REPO_CLONED == 'true'
        run: |
          cd seminar-gitops
          git push origin HEAD:main
