name: Auto Rollback on Argo CD Failure

on:
  repository_dispatch:
    types: [argo-degraded]

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print received data
        run: |
          echo "App: ${{ github.event.client_payload.app }}"
          echo "Failed Revision: ${{ github.event.client_payload.failed_revision }}"
          echo "Healthy Revision: ${{ github.event.client_payload.healthy_revision }}"

      - name: Set Git configuration
        run: |
          git config user.name "GitOps Bot"
          git config user.email "gitops-bot@example.com"

      - name: Checkout to main branch
        run: |
          git checkout main

      - name: Revert to healthy commit
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "Reverting to commit: ${{ github.event.client_payload.healthy_revision }}"
          git revert --no-commit ${{ github.event.client_payload.failed_revision }}..${{ github.event.client_payload.healthy_revision }} || true
          git commit -m "Auto rollback to healthy commit ${{ github.event.client_payload.healthy_revision }} after degraded state"
          git push origin main

      - name: Verify rollback
        run: |
          git log -1
