name: Auto Rollback on Argo CD Failure

on:
  repository_dispatch:
    types: [argo-degraded]

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Print received data from webhook
        run: |
          echo "App: ${{ github.event.client_payload.app }}"
          echo "Failed Revision: ${{ github.event.client_payload.failed_revision }}"
          echo "Last Healthy Commit: ${{ github.event.client_payload.healthy_revision }}"

      - name: Get latest commit
        run: git log -1

      - name: Rollback to Last Healthy Commit
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          LAST_HEALTHY_COMMIT: ${{ github.event.client_payload.healthy_revision }}
        run: |
          echo "Reverting to commit: $LAST_HEALTHY_COMMIT"
          git config user.name "GitOps Bot"
          git config user.email "gitops-bot@example.com"

          # In ra các commit trước khi revert
          git log --oneline -10

          # Kiểm tra commit hợp lệ
          if [ -z "$LAST_HEALTHY_COMMIT" ]; then
            echo "Error: No healthy commit found!"
            exit 1
          fi

          # Thực hiện revert commit
          git revert --no-commit HEAD..$LAST_HEALTHY_COMMIT || true
          git commit -m "Auto rollback to healthy commit $LAST_HEALTHY_COMMIT after degraded state"

          # Đẩy thay đổi lên GitHub
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin HEAD:main

      - name: Verify rollback
        run: |
          echo "Verifying rollback..."
          git log -1
